jobs:
  autograding:
    name: autograding
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: wadefagen/autograding@v1
      with:
        path: mp6/
        test_suite: autograding
  extra_credit:
    name: extra_credit
    needs:
    - autograding
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: wadefagen/autograding@v1
      with:
        path: mp6/
        test_suite: extra_credit        
name: mp6 autograding
'on':
  push:
    paths: mp6/**
